/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmationDialog: typeof import('./src/components/ui/ConfirmationDialog.vue')['default']
    copy: typeof import('./src/components/layout/TheHeader copy.vue')['default']
    ImageWithText: typeof import('./src/components/ui/ImageWithText.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
    TravelCard: typeof import('./src/components/ui/TravelCard.vue')['default']
    TravelInformationCard: typeof import('./src/components/ui/TravelInformationCard.vue')['default']
  }
}
